{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "ish-monitoring-oracledb-exporter.fullname" . }}
  labels:
    app: {{ template "ish-monitoring-oracledb-exporter.name" . }}
    chart: {{ template "ish-monitoring-oracledb-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.rbac.pspEnabled }}
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "ish-monitoring-oracledb-exporter.fullname" . }}]
{{- end }}
{{- end }}
