{{- if .Values.oracle.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ish-monitoring-oracledb-exporter.fullname" . }}
  labels:
    app: {{ template "ish-monitoring-oracledb-exporter.name" . }}
    chart: {{ template "ish-monitoring-oracledb-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  oracle_password: {{ .Values.oracle.password | b64enc }}
{{- end -}}
